### ISSUE TITLE
Export Fail: Multiple drives detected returns generic error

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#1021]
## Description
As a Journalist user, I go to click "Export" on a file. I have 2 drives plugged into my laptop, one correctly provisioned and one not. One of two scenarios happens:
1. If this is my first time trying that, I'll go to the "Insert Encrypted Drive" screen, click Continue, and then the below screen is returned. Or...
2. If this is my second time trying that, I'll simply get this screen immediately after clicking "Export."

![image](https://user-images.githubusercontent.com/8262612/77706174-e2366700-6f7e-11ea-92eb-3e96675ed9e2.png)

## STR
1. On a non-prod machine with the 25 March nightly running...
2. Go to Export a file with 2 drives attached—one correctly encrypted, the other, not
3. Continue until the first Error appears
4. Try it again

## Expected
There should be 2 distinct error messages for this screen...
1. (speak to too many drives on the `sd-devices` VM) Something like... "Too many devices detected. Unplug whichever device you do not want to export your file to."
2. (speak to incorrectly formatted drive) "Either that drive is not correctly encrypted or there is something else wrong with it." NOTE: Current error text does not include the word "correctly," which I feel is important—and shd maybe open a different issue for?

**Comment by eloquence** [comment]
This is a known issue until https://github.com/freedomofpress/securedrop-export/issues/25 is fixed. See also discussion in #21.

**Comment by ninavizz** [comment]
#25 speaks only to multiple luks-encrypted devices. I'm a Mac user, so have multiple "encrypted devices" tooting around. 

If more than 1 device is detected, it was discussed a while ago seeing a simple error message thrown to the user, speaking to that. After reading through the detailed comments in freedomofpress/securedrop-export#25 and freedomofpress/securedrop-export#21  I'm still not understanding why a  simple "Too many devices, pick one" message cannot be displayed.

My read on the comments is that a much smarter solution is being targeted, while overlooking the simpler intermediary option of the "Too many devices, pick one and unplug the others" option.

**Comment by eloquence** [comment]
Not at all, I agree that having an error message for this case is a useful first iteration, https://github.com/freedomofpress/securedrop-export/issues/25 describes the status code we need in order to do so (it may need re-scoping to also handle the case of non-LUKS block devices being attached).
